[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs_18", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "chmod +x start.sh",
    "chmod +x railway-start.sh"
]

[start]
cmd = "bash railway-start.sh"
