[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs_18"]

[phases.build]
cmds = [
    "chmod +x railway-simple-build.sh",
    "bash railway-simple-build.sh"
]

[start]
cmd = "bash railway-safe-start.sh"
