[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs_20", "postgresql"]

[phases.build]
cmds = [
    "chmod +x railway-build.sh",
    "bash railway-build.sh"
]

[start]
cmd = "bash railway-start.sh"
