[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs_20"]

[phases.build]
cmds = [
    "chmod +x safe-build.sh",
    "bash safe-build.sh"
]

[start]
cmd = "bash railway-start.sh"
