[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs_20", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "cp .env.build .env",
    "composer install --no-dev --optimize-autoloader --no-interaction --no-scripts",
    "npm ci --silent"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "npm run build || echo 'Build failed, continuing...'",
    "rm .env",
    "cp .env.example .env",
    "chmod +x railway-start.sh"
]

[start]
cmd = "bash railway-start.sh"
