[build]
builder = "NIXPACKS"

[build.env]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"
  APP_ENV = "production"
  ASSET_URL = "https://laravel-ecommerce-production-aa25.up.railway.app"

[phases.build]
commands = [
    "echo 'Node version:'",
    "node -v",
    "echo 'NPM version:'", 
    "npm -v",
    "echo 'Installing PHP dependencies...'",
    "composer install --no-dev --optimize-autoloader",
    "echo 'Caching Laravel config...'",
    "php artisan config:cache",
    "php artisan route:cache",
    "echo 'Installing Node dependencies...'",
    "npm ci",
    "echo 'Building frontend assets...'",
    "npm run build",
    "echo 'Build completed successfully!'",
    "ls -la public/build/ || echo 'Build directory not found'",
    "ls -la public/build/assets/ || echo 'Assets directory not found'"
]

[phases.deploy]
commands = [
  "echo 'Clearing config and cache...'",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "echo 'Starting database migration...'",
  "php artisan migrate:fresh --force",
  "echo 'Migration completed, checking tables...'",
  "php artisan migrate:status",
  "echo 'Starting database seeding...'",
  "php artisan db:seed --force",
  "echo 'Optimizing application...'",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "echo 'Testing database connection...'",
  "php artisan tinker --execute=\"echo 'Database tables: ' . implode(', ', \\Illuminate\\Support\\Facades\\Schema::getTableListing());\"",
  "echo 'Deployment completed successfully!'"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
