[build]
builder = "NIXPACKS"

[build.env]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"
  APP_ENV = "production"
  ASSET_URL = "https://laravel-ecommerce-production-aa25.up.railway.app"

[phases.build]
commands = [
    "echo '=== Environment Check ==='",
    "node -v",
    "npm -v",
    "pwd",
    "echo '=== Installing PHP dependencies ==='",
    "composer install --no-dev --optimize-autoloader",
    "echo '=== Installing Node dependencies ==='",
    "npm ci --verbose",
    "echo '=== Checking package.json ==='",
    "cat package.json",
    "echo '=== Checking vite.config.ts ==='",
    "cat vite.config.ts",
    "echo '=== Clearing previous build ==='",
    "rm -rf public/build",
    "echo '=== Running Vite Build with verbose output ==='",
    "npm run build --verbose",
    "echo '=== Checking build results ==='",
    "ls -la public/",
    "ls -la public/build/ || echo 'ERROR: Build directory not found'",
    "ls -la public/build/assets/ || echo 'ERROR: Assets directory not found'",
    "cat public/build/manifest.json || echo 'ERROR: Manifest file not found'",
    "echo '=== Build process completed ==='",
    "find public/build -name '*.js' -o -name '*.css' | head -10 || echo 'No built assets found'"
]

[phases.deploy]
commands = [
  "echo 'Starting database migration...'",
  "php artisan migrate:fresh --force",
  "echo 'Migration completed, checking tables...'",
  "php artisan migrate:status",
  "echo 'Starting database seeding...'",
  "php artisan db:seed --force",
  "echo 'Optimizing application for production...'",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "echo 'Testing database connection...'",
  "php artisan tinker --execute=\"echo 'Database tables: ' . implode(', ', \\Illuminate\\Support\\Facades\\Schema::getTableListing());\"",
  "echo 'Deployment completed successfully!'"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
