[build]
builder = "NIXPACKS"

[build.env]
  NODE_VERSION = "20"
  PHP_VERSION = "8.2"

[phases.setup]
commands = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
commands = [
  "php artisan config:cache",
  "php artisan route:cache",
  "npm install",
  "export NODE_OPTIONS=--openssl-legacy-provider",
  "npm run build"
]

[phases.deploy]
commands = [
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
