[build]
builder = "NIXPACKS"

[build.env]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"

[phases.build]
commands = [
    "node -v",
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "npm ci",
  "export NODE_OPTIONS=--openssl-legacy-provider",
  "npm run build"
]

[phases.deploy]
commands = [
  "echo 'Clearing config and cache...'",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "echo 'Starting database migration...'",
  "php artisan migrate:fresh --force",
  "echo 'Migration completed, checking tables...'",
  "php artisan migrate:status",
  "echo 'Starting database seeding...'",
  "php artisan db:seed --force",
  "echo 'Optimizing application...'",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "echo 'Testing database connection...'",
  "php artisan tinker --execute=\"echo 'Database tables: ' . implode(', ', \\Illuminate\\Support\\Facades\\Schema::getTableListing());\"",
  "echo 'Deployment completed successfully!'"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
