[build]
builder = "NIXPACKS"

[build.env]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"

[phases.build]
commands = [
    "node -v",
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "npm ci",
  "export NODE_OPTIONS=--openssl-legacy-provider",
  "npm run build"
]

[phases.deploy]
commands = [
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan migrate:fresh --force --seed",
  "php artisan migrate:status"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
